Virtualbox 6.1 support
cloudfoundry/bosh-virtualbox-cpi-release pull request #20
Opened 2021-09-21 12:22 UTC by rkoster

Addresses #18 by adding SATA disk controller support.

2021-09-21 13:57 UTC, ramonskie commented on src/bosh-virtualbox-cpi/vm/portdevices/port_device.go
>  	controller string // e.g. scsi, ide
missing sata

2021-09-21 15:55 UTC, bgandon requested changes
Overall, I think we should stick to the original blobstore in this PR, even though I understand `git lfs` local blobstore is handy for testing. Let me know if you can't get a hand on the AWS blobstore credentials.

2021-09-22 08:01 UTC, ramonskie commented on jobs/virtualbox_cpi/spec
> +    description: "For some reason IDE controller seems to be more reliable. Available: scsi, ide or sata."
already solved and can be ignored

2021-09-27 15:29 UTC, rkoster commented
Trigger cfgit-bot

2021-09-27 15:56 UTC, bgandon approved these changes

2021-09-27 16:57 UTC, merged