Bridged networking feature
cloudfoundry/bosh-virtualbox-cpi-release pull request #23
Opened 2021-10-13 16:49 UTC by bgandon

This PR is extracted from #17, focusing only on the new “bridged networking” feature. The work has been rebased on top of #22.

Original PR description by @ships in #17:
> - you had a WIP branch on bridged networks topic which I have progressed further. it is working for me but may not be complete; please give feedback at your convenience.
> - right now, you cannot enable or create bridged networks -- so it is only useful in cases where the bridged interface already exists.

Plus, we've gathered here the documentation proposed by @aussielunix in aussielunix@4bc4844.

2021-10-18 09:44 UTC, rkoster requested changes
When trying out these changes I'm getting:
```
Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-3aec8f82-4493-4e13-63ef-6674f124c0b3':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating VM with agent ID '{{a2de8839-3e4f-4b05-78ea-06610d254e40}}': Configuring NIC
s: Expected to find network 'en0'","ok_to_retry":false}
````

Had to change `network_device: "en0: Wi-Fi (Wireless)"` to make it work. Maybe add some docs on how to find the right device name.

2021-10-18 09:44 UTC, rkoster commented on docs/networks-bridged.md
> +network_device: en0
Maybe add a note that this network_device name can be found using `VBoxManage list bridgedifs` . In my case on MacOS I had to use `network_device: "en0: Wi-Fi (Wireless)"`.

2021-10-18 09:44 UTC, rkoster commented on src/bosh-virtualbox-cpi/driver/ssh_runner_test.go
> +		}
Unrelated to this PR

2021-10-18 09:44 UTC, rkoster commented on src/bosh-virtualbox-cpi/driver/ssh_runner_test.go
> +				Host:       testSSHRunnerHost,
Unrelated to this PR

2021-10-19 14:44 UTC, ramonskie approved these changes

2021-10-19 14:44 UTC, merged